import { ROUTES } from '@/constants/routes'
import { ROLES } from '@/constants/roles'

const { ADMIN, EMPLOYEE, PROCUREMENT_MANAGER, COMPLIANCE_OFFICER, AUDITOR } = ROLES

export const routeConfig = [
  {
    path: ROUTES.DASHBOARD,
    key: 'dashboard',
    label: 'Dashboard',
    allowedRoles: [ADMIN, EMPLOYEE, PROCUREMENT_MANAGER, COMPLIANCE_OFFICER, AUDITOR],
    lazy: () => import('@/features/dashboard/pages/RoleDashboardPage'),
  },
  {
    path: ROUTES.EMPLOYEE_DASHBOARD,
    key: 'employee-dashboard',
    label: 'Employee Dashboard',
    allowedRoles: [ADMIN, EMPLOYEE],
    lazy: () => import('@/features/employee/pages/EmployeeDashboard'),
  },
  {
    path: ROUTES.PROCUREMENT_DASHBOARD,
    key: 'procurement-dashboard',
    label: 'Procurement Dashboard',
    allowedRoles: [ADMIN, PROCUREMENT_MANAGER],
    lazy: () => import('@/features/procurement/pages/ProcurementDashboard'),
  },
  {
    path: ROUTES.COMPLIANCE_DASHBOARD,
    key: 'compliance-dashboard',
    label: 'Compliance Dashboard',
    allowedRoles: [ADMIN, COMPLIANCE_OFFICER],
    lazy: () => import('@/features/compliance/pages/ComplianceDashboard'),
  },
  {
    path: ROUTES.AUDIT_DASHBOARD,
    key: 'audit-dashboard',
    label: 'Audit Dashboard',
    allowedRoles: [ADMIN, AUDITOR],
    lazy: () => import('@/features/audit/pages/AuditDashboard'),
  },
  {
    path: ROUTES.ADMIN_DASHBOARD,
    key: 'admin-dashboard',
    label: 'Admin Dashboard',
    allowedRoles: [ADMIN],
    lazy: () => import('@/features/admin/pages/AdminDashboard'),
  },
  {
    path: ROUTES.PROFILE,
    key: 'profile',
    label: 'Profile',
    allowedRoles: [ADMIN, EMPLOYEE, PROCUREMENT_MANAGER, COMPLIANCE_OFFICER, AUDITOR],
    lazy: () => import('@/features/settings/SettingsPage'),
  },
  {
    path: ROUTES.PROCUREMENT,
    key: 'procurement',
    label: 'Procurement',
    allowedRoles: [ADMIN, PROCUREMENT_MANAGER, EMPLOYEE],
    lazy: () => import('@/features/procurement/pages/ProcurementListPage'),
  },
  {
    path: ROUTES.PROCUREMENT_CREATE,
    key: 'procurement-create',
    label: 'Create Procurement',
    allowedRoles: [ADMIN, PROCUREMENT_MANAGER, EMPLOYEE],
    lazy: () => import('@/features/procurement/pages/CreateProcurementPage'),
  },
  {
    path: ROUTES.PROCUREMENT_EDIT,
    key: 'procurement-edit',
    label: 'Edit Procurement',
    allowedRoles: [ADMIN, PROCUREMENT_MANAGER],
    lazy: () => import('@/features/procurement/pages/EditProcurementPage'),
  },
  {
    path: ROUTES.PROCUREMENT_DETAIL,
    key: 'procurement-detail',
    label: 'Procurement Detail',
    allowedRoles: [ADMIN, PROCUREMENT_MANAGER, EMPLOYEE, AUDITOR],
    lazy: () => import('@/features/procurement/pages/ProcurementDetailsPage'),
  },
  {
    path: ROUTES.VENDORS,
    key: 'vendors',
    label: 'Vendors',
    allowedRoles: [ADMIN, PROCUREMENT_MANAGER, COMPLIANCE_OFFICER, AUDITOR],
    lazy: () => import('@/features/vendors/VendorPage'),
  },
  {
    path: ROUTES.VENDOR_DETAIL,
    key: 'vendor-detail',
    label: 'Vendor Detail',
    allowedRoles: [ADMIN, PROCUREMENT_MANAGER, COMPLIANCE_OFFICER, AUDITOR],
    lazy: () => import('@/features/vendors/VendorDetailPage'),
  },
  {
    path: ROUTES.RISK,
    key: 'risk',
    label: 'Risk Center',
    allowedRoles: [ADMIN, COMPLIANCE_OFFICER, AUDITOR],
    lazy: () => import('@/features/risk/RiskPage'),
  },
  {
    path: ROUTES.COMPLIANCE,
    key: 'compliance',
    label: 'Compliance Center',
    allowedRoles: [ADMIN, COMPLIANCE_OFFICER, AUDITOR],
    lazy: () => import('@/features/compliance/CompliancePage'),
  },
  {
    path: ROUTES.AUDIT,
    key: 'audit',
    label: 'Audit Center',
    allowedRoles: [ADMIN, AUDITOR],
    lazy: () => import('@/features/audit/AuditPage'),
  },
  {
    path: ROUTES.ADMIN,
    key: 'admin',
    label: 'Administrator Workspace',
    allowedRoles: [ADMIN],
    lazy: () => import('@/features/admin/AdminWorkspacePage'),
  },
  {
    path: ROUTES.REPORTS,
    key: 'reports',
    label: 'Reporting Center',
    allowedRoles: [ADMIN, PROCUREMENT_MANAGER, COMPLIANCE_OFFICER, AUDITOR],
    lazy: () => import('@/features/reports/ReportPage'),
  },
  {
    path: ROUTES.NOTIFICATIONS,
    key: 'notifications',
    label: 'Notifications',
    allowedRoles: [ADMIN, EMPLOYEE, PROCUREMENT_MANAGER, COMPLIANCE_OFFICER, AUDITOR],
    lazy: () => import('@/features/notifications/NotificationPage'),
  },
  {
    path: ROUTES.APPROVALS,
    key: 'approvals',
    label: 'Approvals',
    allowedRoles: [ADMIN, PROCUREMENT_MANAGER],
    lazy: () => import('@/features/procurement/ApprovalsPage'),
  },
  {
    path: ROUTES.SETTINGS,
    key: 'settings',
    label: 'Settings',
    allowedRoles: [ADMIN, EMPLOYEE, PROCUREMENT_MANAGER, COMPLIANCE_OFFICER, AUDITOR],
    lazy: () => import('@/features/settings/SettingsPage'),
  },
]

export const publicRoutes = [
  { path: ROUTES.LOGIN, lazy: () => import('@/features/auth/LoginPage') },
  { path: ROUTES.SIGNUP, lazy: () => import('@/features/auth/SignupPage') },
  { path: ROUTES.FORGOT_PASSWORD, lazy: () => import('@/features/auth/ForgotPasswordPage') },
  { path: ROUTES.RESET_PASSWORD, lazy: () => import('@/features/auth/ResetPasswordPage') },
  { path: ROUTES.SESSION_EXPIRED, lazy: () => import('@/features/auth/SessionExpiredPage') },
]
