import { ROUTES } from './routes'
import { ROLES } from './roles'

const { ADMIN, EMPLOYEE, PROCUREMENT_MANAGER, COMPLIANCE_OFFICER, AUDITOR } = ROLES

export const MENU_MODULES = {
  DASHBOARD: 'dashboard',
  PROCUREMENT: 'procurement',
  VENDORS: 'vendors',
  RISK: 'risk',
  COMPLIANCE: 'compliance',
  AUDIT: 'audit',
  REPORTS: 'reports',
  ADMIN: 'admin',
  NOTIFICATIONS: 'notifications',
  APPROVALS: 'approvals',
  SETTINGS: 'settings',
}

export const MODULE_LABELS = {
  [MENU_MODULES.DASHBOARD]: 'Dashboard',
  [MENU_MODULES.PROCUREMENT]: 'Procurement Workspace',
  [MENU_MODULES.VENDORS]: 'Vendor Governance',
  [MENU_MODULES.RISK]: 'Risk Center',
  [MENU_MODULES.COMPLIANCE]: 'Compliance Center',
  [MENU_MODULES.AUDIT]: 'Audit Center',
  [MENU_MODULES.REPORTS]: 'Reporting Center',
  [MENU_MODULES.ADMIN]: 'Administrator Workspace',
  [MENU_MODULES.NOTIFICATIONS]: 'Notification Center',
  [MENU_MODULES.APPROVALS]: 'Approval Workbench',
  [MENU_MODULES.SETTINGS]: 'Settings',
}

export const ROUTE_TO_MODULE = {
  [ROUTES.DASHBOARD]: MENU_MODULES.DASHBOARD,
  [ROUTES.PROCUREMENT]: MENU_MODULES.PROCUREMENT,
  [ROUTES.VENDORS]: MENU_MODULES.VENDORS,
  [ROUTES.RISK]: MENU_MODULES.RISK,
  [ROUTES.COMPLIANCE]: MENU_MODULES.COMPLIANCE,
  [ROUTES.AUDIT]: MENU_MODULES.AUDIT,
  [ROUTES.REPORTS]: MENU_MODULES.REPORTS,
  [ROUTES.ADMIN]: MENU_MODULES.ADMIN,
  [ROUTES.NOTIFICATIONS]: MENU_MODULES.NOTIFICATIONS,
  [ROUTES.APPROVALS]: MENU_MODULES.APPROVALS,
  [ROUTES.SETTINGS]: MENU_MODULES.SETTINGS,
}
