import { ROLES } from './roles'
import { ROUTES } from './routes'

const { ADMIN, EMPLOYEE, PROCUREMENT_MANAGER, COMPLIANCE_OFFICER, AUDITOR } = ROLES

export const PERMISSIONS = {
  procurement: {
    view: [ADMIN, EMPLOYEE, PROCUREMENT_MANAGER, AUDITOR],
    create: [ADMIN, EMPLOYEE, PROCUREMENT_MANAGER],
    edit: [ADMIN, PROCUREMENT_MANAGER],
    delete: [ADMIN],
    approve: [ADMIN, PROCUREMENT_MANAGER],
    export: [ADMIN, PROCUREMENT_MANAGER, AUDITOR],
  },
  vendors: {
    view: [ADMIN, PROCUREMENT_MANAGER, COMPLIANCE_OFFICER, AUDITOR],
    create: [ADMIN, PROCUREMENT_MANAGER],
    edit: [ADMIN, PROCUREMENT_MANAGER],
    delete: [ADMIN],
    export: [ADMIN, PROCUREMENT_MANAGER, AUDITOR],
  },
  risk: {
    view: [ADMIN, COMPLIANCE_OFFICER, AUDITOR],
    create: [ADMIN, COMPLIANCE_OFFICER],
    edit: [ADMIN, COMPLIANCE_OFFICER],
    delete: [ADMIN],
    export: [ADMIN, COMPLIANCE_OFFICER, AUDITOR],
  },
  compliance: {
    view: [ADMIN, COMPLIANCE_OFFICER, AUDITOR],
    create: [ADMIN, COMPLIANCE_OFFICER],
    edit: [ADMIN, COMPLIANCE_OFFICER],
    delete: [ADMIN],
    export: [ADMIN, COMPLIANCE_OFFICER, AUDITOR],
  },
  audit: {
    view: [ADMIN, AUDITOR],
    create: [ADMIN, AUDITOR],
    edit: [ADMIN],
    delete: [ADMIN],
    export: [ADMIN, AUDITOR],
  },
  reports: {
    view: [ADMIN, PROCUREMENT_MANAGER, COMPLIANCE_OFFICER, AUDITOR],
    export: [ADMIN, PROCUREMENT_MANAGER, COMPLIANCE_OFFICER, AUDITOR],
    save: [ADMIN, PROCUREMENT_MANAGER, COMPLIANCE_OFFICER, AUDITOR],
    delete: [ADMIN],
  },
  settings: {
    viewProfile: [ADMIN, EMPLOYEE, PROCUREMENT_MANAGER, COMPLIANCE_OFFICER, AUDITOR],
    editProfile: [ADMIN, EMPLOYEE, PROCUREMENT_MANAGER, COMPLIANCE_OFFICER, AUDITOR],
    manageUsers: [ADMIN],
    manageRoles: [ADMIN],
  },
}

export const ROUTE_PERMISSIONS = {
  [ROUTES.DASHBOARD]: [ADMIN, EMPLOYEE, PROCUREMENT_MANAGER, COMPLIANCE_OFFICER, AUDITOR],
  [ROUTES.EMPLOYEE_DASHBOARD]: [ADMIN, EMPLOYEE],
  [ROUTES.PROCUREMENT_DASHBOARD]: [ADMIN, PROCUREMENT_MANAGER],
  [ROUTES.COMPLIANCE_DASHBOARD]: [ADMIN, COMPLIANCE_OFFICER],
  [ROUTES.AUDIT_DASHBOARD]: [ADMIN, AUDITOR],
  [ROUTES.ADMIN_DASHBOARD]: [ADMIN],
  [ROUTES.PROFILE]: [ADMIN, EMPLOYEE, PROCUREMENT_MANAGER, COMPLIANCE_OFFICER, AUDITOR],
  [ROUTES.PROCUREMENT]: [ADMIN, PROCUREMENT_MANAGER, EMPLOYEE],
  [ROUTES.PROCUREMENT_CREATE]: [ADMIN, PROCUREMENT_MANAGER, EMPLOYEE],
  [ROUTES.PROCUREMENT_DETAIL]: [ADMIN, PROCUREMENT_MANAGER, EMPLOYEE, AUDITOR],
  [ROUTES.PROCUREMENT_EDIT]: [ADMIN, PROCUREMENT_MANAGER],
  [ROUTES.APPROVALS]: [ADMIN, PROCUREMENT_MANAGER],
  [ROUTES.VENDORS]: [ADMIN, PROCUREMENT_MANAGER, COMPLIANCE_OFFICER, AUDITOR],
  [ROUTES.VENDOR_DETAIL]: [ADMIN, PROCUREMENT_MANAGER, COMPLIANCE_OFFICER, AUDITOR],
  [ROUTES.RISK]: [ADMIN, COMPLIANCE_OFFICER, AUDITOR],
  [ROUTES.COMPLIANCE]: [ADMIN, COMPLIANCE_OFFICER],
  [ROUTES.AUDIT]: [ADMIN, AUDITOR],
  [ROUTES.REPORTS]: [ADMIN, PROCUREMENT_MANAGER, COMPLIANCE_OFFICER, AUDITOR],
  [ROUTES.NOTIFICATIONS]: [ADMIN, EMPLOYEE, PROCUREMENT_MANAGER, COMPLIANCE_OFFICER, AUDITOR],
  [ROUTES.SETTINGS]: [ADMIN, EMPLOYEE, PROCUREMENT_MANAGER, COMPLIANCE_OFFICER, AUDITOR],
}

export function hasPermission(userRole, module, action) {
  return PERMISSIONS[module]?.[action]?.includes(userRole) ?? false
}
